version: '3.2'
services:

  identifier:
    image: semtech/mu-identifier:1.9.1
    ports:
      - "80:80"
    links:
      - dispatcher:dispatcher

  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    volumes:
      - ./config/dispatcher:/config

  login:
    image: semtech/mu-login-service:2.9.1
    links:
      - db:database

  #registration:
  #  image: semtech/mu-registration-service:2.6.0
  #  links:
  #    - db:database

  # database, the single source of truth
  db:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/virtuoso:/data
      - ./config/virtuoso/toLoad:/data/toLoad

  resource:
    image: semtech/mu-cl-resources:1.20.0
    links:
      - db:database
    volumes:
      - ./config/resources:/config
    ports:
      - "8885:80"

  frontend:
    environment:
      PUBLIC_URL: "/frontend/"
    build: ./frontend

  backend:
    build: ./backend


